### ISSUE TITLE
无法创建用户

### ISSUE THREAD

**Issue by geq1fan** [babylikebird/common-admin#2]
注册完用户再登陆时，页面没有反应，后台抛异常。
目前只能用super用户登陆。

**Comment by yangxiufeng666** [comment]
后台系统没有实现注册功能，super用户登录后创建用户

**Comment by yangxiufeng666** [comment]
你可以自己实现注册功能 @geqifan1

**Comment by geq1fan** [comment]
![q3 9c w_m3x6uwta 5k 5ae](https://user-images.githubusercontent.com/29982379/34557059-f2f7ae54-f173-11e7-9776-e6e9dc3d2641.png)
我想添加菜单到左边的窗口去，但是发现并没有反应。
还有这个层级和顺序有什么作用？
